/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xutJztT0Oti
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu, DropdownMenuRadioItem } from "@/components/ui/dropdown-menu"
import { Checkbox } from "@/components/ui/checkbox"
import { CardTitle, CardDescription, CardHeader, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"

export function dashboard() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-6 px-4 md:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="Mentor Avatar" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <h1 className="text-2xl font-bold">John Doe</h1>
              <p className="text-gray-400">Mentor</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button size="icon" variant="ghost">
                  <FilterIcon className="h-6 w-6" />
                  <span className="sr-only">Filter projects</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <DropdownMenuLabel>Filter by</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuCheckboxItem>
                  <Checkbox />
                  Frontend{"\n                            "}
                </DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>
                  <Checkbox />
                  Backend{"\n                            "}
                </DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>
                  <Checkbox />
                  Mobile{"\n                            "}
                </DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>
                  <Checkbox />
                  Design{"\n                            "}
                </DropdownMenuCheckboxItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button size="icon" variant="ghost">
                  <ListIcon className="h-6 w-6" />
                  <span className="sr-only">Sort projects</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <DropdownMenuLabel>Sort by</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuRadioItem value="newest">Newest</DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="oldest">Oldest</DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="title">Title</DropdownMenuRadioItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-4 md:p-8">
        <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Project 1</CardTitle>
              <CardDescription>A web application that helps users manage their tasks and projects.</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-medium text-blue-500 hover:underline" href="#">
                View Project
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Project 2</CardTitle>
              <CardDescription>A mobile app that helps users track their fitness activities.</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-medium text-blue-500 hover:underline" href="#">
                View Project
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Project 3</CardTitle>
              <CardDescription>
                A design system for a SaaS platform, including UI components and guidelines.
              </CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-medium text-blue-500 hover:underline" href="#">
                View Project
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Project 4</CardTitle>
              <CardDescription>A backend API for a e-commerce platform, handling orders and inventory.</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-medium text-blue-500 hover:underline" href="#">
                View Project
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Project 5</CardTitle>
              <CardDescription>A cross-platform mobile app for a social media platform.</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-medium text-blue-500 hover:underline" href="#">
                View Project
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Project 6</CardTitle>
              <CardDescription>A data visualization dashboard for a business intelligence platform.</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link className="font-medium text-blue-500 hover:underline" href="#">
                View Project
              </Link>
            </CardFooter>
          </Card>
        </div>
      </main>
    </div>
  )
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}
