/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kFmzj04lYL0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu, DropdownMenuRadioItem } from "@/components/ui/dropdown-menu"
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card, CardTitle } from "@/components/ui/card"

export function mentordashboard() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <img
            alt="Mentor Avatar"
            className="rounded-full"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
          <div>
            <h1 className="text-lg font-semibold">John Doe</h1>
            <p className="text-gray-400 text-sm">Mentor</p>
          </div>
        </div>
        <nav className="flex items-center gap-6">
          <Link className="text-gray-400 hover:text-white" href="#">
            Dashboard
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            Projects
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            Mentees
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            Analytics
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            Settings
          </Link>
        </nav>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-6">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-semibold">Projects</h2>
            <div className="flex items-center gap-4">
              <Input
                className="bg-white dark:bg-gray-950 px-4 py-2 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent"
                placeholder="Search projects..."
                type="search"
              />
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="flex items-center gap-2" variant="outline">
                    <FilterIcon className="h-5 w-5" />
                    Filter
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  <DropdownMenuLabel>Filter by status</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuCheckboxItem>Active</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>Completed</DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem>Archived</DropdownMenuCheckboxItem>
                </DropdownMenuContent>
              </DropdownMenu>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="flex items-center gap-2" variant="outline">
                    <ListIcon className="h-5 w-5" />
                    Sort
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  <DropdownMenuLabel>Sort by</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuRadioItem value="name">Name</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="mentees">Mentees</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="status">Status</DropdownMenuRadioItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold">Project A</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">This is a description of Project A.</p>
                </div>
                <Badge variant="success">Active</Badge>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <span className="text-gray-500 dark:text-gray-400">10 Mentees</span>
                  </div>
                  <Button size="sm" variant="ghost">
                    View
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold">Project B</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">This is a description of Project B.</p>
                </div>
                <Badge variant="success">Active</Badge>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <span className="text-gray-500 dark:text-gray-400">15 Mentees</span>
                  </div>
                  <Button size="sm" variant="ghost">
                    View
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold">Project C</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">This is a description of Project C.</p>
                </div>
                <Badge variant="danger">Completed</Badge>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <span className="text-gray-500 dark:text-gray-400">8 Mentees</span>
                  </div>
                  <Button size="sm" variant="ghost">
                    View
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold">Project D</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">This is a description of Project D.</p>
                </div>
                <Badge variant="warning">Archived</Badge>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <span className="text-gray-500 dark:text-gray-400">12 Mentees</span>
                  </div>
                  <Button size="sm" variant="ghost">
                    View
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold">Project E</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">This is a description of Project E.</p>
                </div>
                <Badge variant="success">Active</Badge>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <span className="text-gray-500 dark:text-gray-400">18 Mentees</span>
                  </div>
                  <Button size="sm" variant="ghost">
                    View
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold">Project F</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">This is a description of Project F.</p>
                </div>
                <Badge variant="danger">Completed</Badge>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <span className="text-gray-500 dark:text-gray-400">6 Mentees</span>
                  </div>
                  <Button size="sm" variant="ghost">
                    View
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      <div className="bg-gray-900 text-white p-6">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Profile</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <img
                  alt="Mentor Avatar"
                  className="rounded-full"
                  height="64"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "64/64",
                    objectFit: "cover",
                  }}
                  width="64"
                />
                <div>
                  <h3 className="text-lg font-semibold">John Doe</h3>
                  <p className="text-gray-400 text-sm">Mentor</p>
                </div>
              </div>
              <div className="mt-4">
                <p className="text-gray-400 text-sm">
                  John is an experienced mentor with a passion for helping others succeed. He has been mentoring for
                  over 5 years and has a proven track record of helping mentees achieve their goals.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Analytics</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div className="flex flex-col items-center">
                  <h4 className="text-2xl font-semibold">25</h4>
                  <p className="text-gray-400 text-sm">Active Projects</p>
                </div>
                <div className="flex flex-col items-center">
                  <h4 className="text-2xl font-semibold">150</h4>
                  <p className="text-gray-400 text-sm">Total Mentees</p>
                </div>
                <div className="flex flex-col items-center">
                  <h4 className="text-2xl font-semibold">$10,000</h4>
                  <p className="text-gray-400 text-sm">Total Earnings</p>
                </div>
                <div className="flex flex-col items-center">
                  <h4 className="text-2xl font-semibold">95%</h4>
                  <p className="text-gray-400 text-sm">Mentee Satisfaction</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Events</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Mentorship Workshop</h4>
                    <p className="text-gray-400 text-sm">May 15, 2023</p>
                  </div>
                  <Button size="sm" variant="outline">
                    RSVP
                  </Button>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Mentee Meetup</h4>
                    <p className="text-gray-400 text-sm">June 1, 2023</p>
                  </div>
                  <Button size="sm" variant="outline">
                    RSVP
                  </Button>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Mentor Networking Event</h4>
                    <p className="text-gray-400 text-sm">July 10, 2023</p>
                  </div>
                  <Button size="sm" variant="outline">
                    RSVP
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
